version: "0.1.0"
name: financial_analysis
services:
  crew_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"

volumes:
  crew_api:
    driver: local
