version: "0.1.0"
name: customer_support_automation
services:
  api_customer_support:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"

volumes:
  api_customer_support:
    driver: local
